# Generated by Django 4.2.7 on 2023-12-04 00:35

from django.db import migrations


def add_recipes(apps, schema_editor):
    Recipe = apps.get_model('base', 'Recipe')
    Category = apps.get_model('base', 'Category')

    Recipe.objects.create(title='Оливье', category=Category.objects.get(name='Салаты'),
                          content='Порезать, перемешать, заправить майонезом')
    Recipe.objects.create(title='Солянка', category=Category.objects.get(name='Супы'),
                          content='Отварить, посалить, дать настоятся')
    Recipe.objects.create(title='Пюрешечка', category=Category.objects.get(name='Второе'),
                          content='Отварить, потолочь, добавить яйца, молоко, масло сливочное')
    Recipe.objects.create(title='Компот', category=Category.objects.get(name='Напитки'),
                          content='Отварить сухофрукты, дать остыть')
    Recipe.objects.create(title='Борщ', category=Category.objects.get(name='Супы'),
                          content='Сварить щи и добавить свеклу')
    Recipe.objects.create(title='Чай', category=Category.objects.get(name='Напитки'),
                          content='В кипяток добавить чай')
    Recipe.objects.create(title='Селёдка под шубой', category=Category.objects.get(name='Салаты'),
                          content='Сложно не делай')


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0002_auto_20231204_0719'),
    ]

    operations = [migrations.RunPython(add_recipes), ]
